apiVersion: skaffold/v2beta19
kind: Config
build:
  tagPolicy:
    sha256: { }
  local:
    push: false
  artifacts:
    - image: local/skaffold_reproducer_dev
      sync:
        infer:
          - '**/*.js'
          - '**/*.ts'
      docker:
        dockerfile: Dockerfile/Dockerfile

deploy:
  helm:
    releases:
      - name: skaffold_reproducer_dev
        chartPath: deployment/dev-remote
        artifactOverrides:
          image: local/workflow-service-dev-1
        imageStrategy:
          helm:
            explicitRegistry: true

profiles:
  # use the cloudbuild profile to build images using Google Cloud Build
  - name: clusterbuild
    build:
      artifacts:
        - image: gitlab.quanticfinancial.com:5050/workflow/q1-workflow-service/dev-repord
          sync:
            infer:
              - '**/*.js'
              - '**/*.ts'
              - 'config.ts'
              - 'seeding.json'
          kaniko:
            cache:
              repo: gitlab.quanticfinancial.com:5050/workflow/q1-workflow-service/dev-repord/cache
            dockerfile: ./Dockerfile/Dockerfile.dev
      cluster:
        namespace: kaniko
        nodeSelector:
          "kubernetes.io/os": linux
          "kaniko": "true"
        dockerConfig:
          secretName: gitlab-secret
          #path: ~/.docker/config.ts
    deploy:
      helm:
        releases:
          - name: skaffold-reproducer-dev
            chartPath: deployment/dev
            artifactOverrides:
              image: gitlab.quanticfinancial.com:5050/workflow/q1-workflow-service/dev-repord
            imageStrategy:
              helm:
                explicitRegistry: true