apiVersion: v2
version: 1.0.0
appVersion: "1.0.0"
name: file-service-statar-deploy
description: A Helm chart for Q1 File Service

dependencies:
  - name: common
    version: 1.0.0
    repository: https://gitlab.quanticfinancial.com/api/v4/projects/50/packages/helm/stable
