# Default values for registry-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: development
version: v1

image:
  registry: gitlab.quanticfinancial.com:5050/statar
  repository: q1-file-service-v2/master
  tag: latest
  pullPolicy: Always
  #pullPolicy: IfNotPresent

ports:
  - containerPort: 3001

fullnameOverride: q1-file-service-v2

nodeSelector:
  "kubernetes.io/os": linux
  "development-nodes": "true"
  "agentpool": "nodepool1"
  "arm-node": "true"
  # "kubernetes.azure.com/mode": user
  #  agentpool: npbase0

imagePullSecrets:
  name: q1regcred

resources:
  limits:
    memory: 4Gi

env:
  PORT: 3001
  NODE_ENV: development
  API_HOST: development.quanticfinancial.com
  AUTH_HOST: auth.quanticfinancial.com
  DB_USERNAME: cpm
  DB_PASSWORD: tf#4bB4&XJ_vUg4d
  DB_PORT: 27017
  DB_HOST: mongodb-service.development-db.svc.cluster.local
  DB_NAME: service_file
  KAFKA_HOST: development-cluster-kafka-bootstrap.development.svc.cluster.local:9092
  KAFKA_CLIENTID: q1-file-service
  KAFKA_TOPIC: dev.upload.process
  AZURE_BLOB_CONNECTION_STRING: "BlobEndpoint=https://kafkafiledevshare.blob.core.windows.net/;QueueEndpoint=https://kafkafiledevshare.queue.core.windows.net/;FileEndpoint=https://kafkafiledevshare.file.core.windows.net/;TableEndpoint=https://kafkafiledevshare.table.core.windows.net/;SharedAccessSignature=sv=2021-06-08&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2023-12-31T23:00:00Z&st=2022-12-31T23:00:00Z&spr=https&sig=H7MEANcYS7lCYv2JJ%2FVzazl%2FwhincLYlLqL3xXBdiXE%3D"


service:
  api: file
  ports:
    - name: q1-file-service-v2
      port: 3001
      targetPort: 3001
  external:
    port: 3001

  http:
    - match:
        - uri:
            prefix: "/api/file/"
          port: 9100
      route:
        - destination:
            host: "file-service-v2.development.svc.cluster.local"
            subset: v1

configmap:
  enabled: true
  pvstorage: true
  pvstorageazfile: true
  #azfstorage: true
  azureFile:
    secretName: azure-secret
    shareName: aksshare
    secretNamespace: default
  volumeMounts:
    mountPath: "/app/uploads"
    subPath: uploads

volume:
  storage: 10Gi

storageName: "pv"

ingress:
  domain: development.quanticfinancial.com