apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ printf "%s-%s" (include "common.fullname" . ) .Values.storageName  }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "common.name" . }}
    helm.sh/chart: {{ include "common.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  capacity:
    storage: {{ .Values.volume.storage }}
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: {{ .Values.configmap.azureFile.secretName }}
    secretNamespace: {{ .Values.configmap.azureFile.secretNamespace }}
    shareName: {{ .Values.configmap.azureFile.shareName }}
    readOnly: false
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1000
    - gid=1000
    - mfsymlinks
    - nobrl

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-%s" ( include "common.fullname" . ) .Values.storageName  }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "common.name" . }}
    helm.sh/chart: {{ include "common.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.volume.storage }}
