# Default values for registry-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: development
version: v1

image:
  registry: gitlab.quanticfinancial.com:5050/microservice
  repository: q1-workflow-service/dev
  tag: latest
  pullPolicy: Always
  #pullPolicy: IfNotPresent

ports:
  - containerPort: 3000

fullnameOverride: q1-workflow-service-dev

nodeSelector:
  "kubernetes.io/os": linux
  "development-nodes": "true"
  "arm-node": "true"
  "agentpool": "nodepool1"
  # "kubernetes.azure.com/mode": user
  #  agentpool: npbase0

imagePullSecrets:
  name: q1regcred

resources:
  requests:
    memory: 1Gi

env:
  PORT: 3001
  NODE_ENV: development
  API_HOST: development.quanticfinancial.com
  AUTH_HOST: auth.quanticfinancial.com
  MONGO_HOST: mongodb-service.development-db.svc.cluster.local
  MONGO_DATABASE: service_workflow
  MONGO_USERNAME: cpm
  MONGO_PASSWORD: tf#4bB4&XJ_vUg4d
  MONGO_PORT: 27017
  KAFKA_HOST: kafka-bootstrap-lb.confluent.svc.cluster.local:9092
  KAFKA_CLIENTID: node-js-boilerplate
  KAFKA_TOPIC: dev.workflow.process
  AZURE_BLOB_CONNECTION_STRING: BlobEndpoint=https://kafkafiledevshare.blob.core.windows.net/;QueueEndpoint=https://kafkafiledevshare.queue.core.windows.net/;FileEndpoint=https://kafkafiledevshare.file.core.windows.net/;TableEndpoint=https://kafkafiledevshare.table.core.windows.net/;SharedAccessSignature=sv=2021-06-08&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2023-12-31T23:00:00Z&st=2022-12-31T23:00:00Z&spr=https&sig=H7MEANcYS7lCYv2JJ%2FVzazl%2FwhincLYlLqL3xXBdiXE%3D

service:
  gateway: mesh-gateway-development
  api: file
  ports:
    - name: workflow-service
      port: 3000
      targetPort: 3000
  external:
    port: 3000

  http:
    - match:
        - uri:
            prefix: "/api/file/"
          port: 9100
        - uri:
            prefix: "/api/upload/"
          port: 9100
        - uri:
            prefix: "/api/file-docs/"
          port: 9100
      route:
        - destination:
            host: "workflow-service.development.svc.cluster.local"
            subset: v1

configmap:
  enabled: true
  pvstorage: true
  pvstorageazfile: true
  #azfstorage: true
  azureFile:
    secretName: azure-secret
    shareName: aksshare
    secretNamespace: default
  volumeMounts:
    mountPath: "/app/uploads"
    subPath: uploads

volume:
  storage: 10Gi

storageName: "pv"

ingress:
  domain: development.quanticfinancial.com
