apiVersion: apps/v1
kind: Deployment
metadata:
  name: skaffold-reporducer
  namespace: development
  labels:
    app: skaffold-reporducer
    app.kubernetes.io/name: skaffold-reporducer
    helm.sh/chart: skaffold-reporducer-1-1.0.0
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skaffold-reporducer
      version: v1
      app.kubernetes.io/name: skaffold-reporducer
  template:
    metadata:
      labels:
        app: skaffold-reporducer
        version: v1
        app.kubernetes.io/name: skaffold-reporducer
      annotations:
        deploymentTime: "20230920111647"
    spec:
      nodeSelector:
        # use whichever nodepool you would like.
        # We select ARM nodepools
        agentpool: nodepool1
        arm-node: "true"
        development-nodes: "true"
        kubernetes.io/os: linux
      containers:
        - name: skaffold-reporducer
          image: "gitlab.quanticfinancial.com:5050/microservice/q1-workflow-service-1/dev-reprod:latest"
          imagePullPolicy: Always
          resources:
            limits:
              memory: 6Gi
            requests:
              memory: 1Gi
      imagePullSecrets:
        - name: q1regcred
