apiVersion: v1
kind: Service
metadata:
  name: skaffold-reproducer
  namespace: development
  labels:
    app: skaffold-reproducer
    app.kubernetes.io/name: skaffold-reproducer
    helm.sh/chart: skaffold-reproducer-1-1.0.0
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - name: skaffold-reproducer
      port: 3000
      targetPort: 3000
  selector:
    app: skaffold-reproducer
