# Default values for registry-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: staging
version: v1

image:
  registry: gitlab.quanticfinancial.com:5050/statar
  repository: q1-file-service/master
  tag: latest
  pullPolicy: Always
  #pullPolicy: IfNotPresent

ports:
  - containerPort: 3001

fullnameOverride: file-service

nodeSelector:
  "kubernetes.io/os": linux
  "development-nodes": "true"
  "arm-node": "true"
  # "kubernetes.azure.com/mode": user
  #  agentpool: npbase0

imagePullSecrets:
  name: q1regcred

resources:
  limits:
    memory: 1Gi

env:
  PORT: 3001
  NODE_ENV: staging
  API_HOST: staging.quanticfinancial.com
  AUTH_HOST: auth.quanticfinancial.com
  DB_USERNAME: cpm
  DB_PASSWORD: "tf#4bB4&XJ_vUg4d"
  DB_PORT: 27017
  DB_HOST: mongodb-service.staging-db.svc.cluster.local
  DB_NAME: service_file
  KAFKA_HOST: development-cluster-kafka-bootstrap.development.svc.cluster.local:9092
  KAFKA_CLIENTID: file-service
  KAFKA_TOPIC: upload.process
  AZURE_BLOB_CONNECTION_STRING: "BlobEndpoint=https://kafkafiledevshare.blob.core.windows.net/;QueueEndpoint=https://kafkafiledevshare.queue.core.windows.net/;FileEndpoint=https://kafkafiledevshare.file.core.windows.net/;TableEndpoint=https://kafkafiledevshare.table.core.windows.net/;SharedAccessSignature=sv=2021-06-08&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2023-12-31T23:00:00Z&st=2022-12-31T23:00:00Z&spr=https&sig=H7MEANcYS7lCYv2JJ%2FVzazl%2FwhincLYlLqL3xXBdiXE%3D"

service:
  gateway: istio-system/mesh-gateway-staging
  api: file
  ports:
    - name: http-file-service
      port: 3001
      targetPort: 3001
  external:
    port: 3001

  http:
    - match:
        - uri:
            prefix: "/api/file/"
          port: 9100
        - uri:
            prefix: "/api/upload/"
          port: 9100
        - uri:
            prefix: "/api/file-docs/"
          port: 9100
      route:
        - destination:
            host: "file-service.staging.svc.cluster.local"
            subset: v1

ingress:
  domain: staging.quanticfinancial.com